// GENERATED by scripts/gen-contract-types.mjs from the calc.v1 JSON Schemas. Do not edit.

// ── calculation-input.v1.schema.json
/** Canonical voyage-calculation input (D-010). The sheet is the saved sheet document exactly as the frontend serialises it (Index.tsx gatherData). organization_id is never accepted from the browser: the server takes it from the JWT. */
export interface CalculationInput {
  contract_version: "calc.v1";
  calculation_id?: string | null; // Optional client UUID; the server generates one when absent.
  sheet_id?: string | null; // Sheet UUID; null for an unsaved sheet.
  segment: "dry_bulk" | "tanker";
  engine_version?: string | null; // Engine version the client expects (informational until M3).
  reference_data_version?: string | null; // Reference-data version the client expects (informational until M3).
  working_sequence: number;
  calculation_date?: string | null; // UTC date (YYYY-MM-DD) for year/date-dependent regulatory rules (D-012). Server uses today (UTC) when absent.
  sheet: SheetDocument;
}

export interface SheetDocument {
  vessel: Vessel;
  sequence: Array<SequenceRow>;
  cargos?: Array<CargoEntry>;
  bunker?: Bunker;
  misc?: Misc;
  hireRate?: number;
  vesselCost?: number;
  netBB?: number;
  applyEuaImpact?: boolean;
  applyFuelEuImpact?: boolean;
  applyUkEtsImpact?: boolean;
  departureUtc?: string;
  autoDistanceEnabled?: boolean;
  notes?: string;
  charterer?: string;
}

export interface Vessel {
  name?: string;
  type?: string;
  imo?: string;
  dwt?: number;
  gt?: number;
  cubic?: number;
  cubicUnit?: string;
  draft?: number;
  tpcTpi?: number;
  hsfoCapability?: boolean;
  hasScrubber?: boolean;
  scrubberCount?: number;
  builtYear?: number;
  builder?: string;
  owner?: string;
  loa?: number;
  beam?: number;
  speedProfile?: "eco" | "full";
  ecoConsumption?: ConsumptionMatrix;
  fullConsumption?: ConsumptionMatrix;
  loadDischIdleSame?: boolean;
  miscMultiplier?: number;
  consumption?: LegacyConsumption;
}

export interface ConsumptionMatrix {
  speed?: MatrixRow;
  hsfo?: MatrixRow;
  vlsfo?: MatrixRow;
  lsmgo?: MatrixRow;
  ae?: MatrixRow;
  aeScrubber?: MatrixRow;
}

export interface MatrixRow {
  ballast?: number;
  laden?: number;
  canal?: number;
  load?: number;
  discharge?: number;
  idle?: number;
  misc1?: number;
  misc2?: number;
}

/** Legacy speed-profile-independent table. Stored by old sheets; not read by the calculation. */
export interface LegacyConsumption {
  speed?: LegacyRow;
  hsfo?: LegacyRow;
  vlsfo?: LegacyRow;
  lsmgo?: LegacyRow;
  ae?: LegacyRow;
  aeScrubber?: LegacyRow;
}

export interface LegacyRow {
  ecoBallast?: number;
  ecoLaden?: number;
  canal?: number;
}

export interface SequenceRow {
  id: number;
  type?: "open" | "port" | "repos";
  operation?: string;
  port?: string;
  portUnloc?: string;
  portId?: number;
  coordinates?: Array<number>;
  season?: string;
  distance?: number;
  distanceSpeedContext?: string;
  ecaDistance?: number;
  ecaDistanceSpeedContext?: string;
  baseSeaTime?: number; // Derived; recomputed, never trusted.
  seaMarginTime?: number; // Derived; recomputed, never trusted.
  ecaTime?: number; // Derived; recomputed, never trusted.
  seaTime?: number; // Derived; recomputed, never trusted.
  totalLegTime?: number; // Derived; recomputed, never trusted.
  timeOverride?: number;
  quantity?: number;
  productivity?: number;
  layTime?: number;
  terms?: string;
  customTermsName?: string;
  turnTime?: number;
  extraTime?: number;
  calculatedPortDays?: number; // Derived; recomputed, never trusted.
  wdaysPortOverride?: number;
  wdaysUnit?: string;
  draft?: number;
  cranes?: number;
  seaMargin?: number;
  bunkeringHsfo?: number;
  bunkeringVlsfo?: number;
  bunkeringLsmgo?: number;
  expDa?: number;
  daOwnerAcct?: number;
  daChartererAcct?: number;
  portMaxDraft?: number;
  ukcPercent?: number;
  stowageFactor?: number;
  portFuelType?: "hsfo" | "vlsfo" | "lsmgo";
  coefficientFactor?: number;
  isEuEea?: boolean;
  portCountry?: string;
  ukEts?: boolean;
  ukZone?: "gb" | "ni" | null;
  weatherDelayHours?: number;
  weatherDelayFailed?: boolean;
  eta?: string;
  legDepartureUtc?: string;
  legArrivalUtc?: string;
  assignedCargoIds?: Array<number>;
}

export interface CargoEntry {
  id: number;
  rate?: number;
  rateType?: "mt" | "lumpsum";
  quantity?: number;
  worldscale?: number;
  voyageCommission?: number;
  tcCommission?: number;
  demurrageRate?: number;
  despatchRate?: number;
  demurrageAmount?: number;
  despatchAmount?: number;
  averageMode?: string;
  laytimeMode?: "average" | "non_reversible" | "cancelled";
  ntcBase?: number;
  gtcTarget?: number;
  netBBOverride?: number;
  stowageFactor?: number;
  cpOverrides?: Record<string, CpOverride>;
  opOverrides?: Record<string, OpOverride>;
}

export interface CpOverride {
  quantity?: number;
  productivity?: number;
  demurrage?: number;
  despatch?: number;
  turnTime?: number;
  extraTime?: number;
  terms?: string;
  coefficientFactor?: number;
  layTime?: number;
}

export interface OpOverride {
  quantity?: number;
  productivity?: number;
  turnTime?: number;
  extraTime?: number;
  terms?: string;
  coefficientFactor?: number;
  cranes?: number;
  expDa?: number;
  layTime?: number;
}

export interface Bunker {
  hsfo?: BunkerPrice;
  vlsfo?: BunkerPrice;
  lsmgo?: BunkerPrice;
  co2Price?: number; // Deprecated; ignored.
  euEtsPrice?: number;
  ukEtsPrice?: number;
  fuelMode?: "average" | "fifo";
  ignoreBOB?: boolean;
  rewardFactor?: number;
  portBunkering?: Array<PortBunkeringEntry>;
  euEtsHsfo?: number;
  euEtsVlsfo?: number;
  euEtsLsmgo?: number;
}

export interface BunkerPrice {
  price?: number;
  robStart?: number;
}

export interface PortBunkeringEntry {
  id?: number;
  portUnloc?: string;
  portName?: string;
  hsfo?: BunkerLot;
  vlsfo?: BunkerLot;
  lsmgo?: BunkerLot;
}

export interface BunkerLot {
  quantity?: number;
  price?: number;
}

export interface Misc {
  miscCost?: number;
  extraFees?: number;
  extraInsurance?: number;
  canalCost1?: number;
  canalFuel?: "hsfo" | "vlsfo" | "lsmgo";
  extraTime?: MiscExtraTime;
}

export interface MiscExtraTime {
  canal1?: ExtraTimeEntry;
}

export interface ExtraTimeEntry {
  mode?: string;
  value?: number;
  unit?: "days" | "hours";
}

// ── calculation-result.v1.schema.json
/** Browser-facing calculation response. result mirrors the frontend VoyageResults shape so the UI can switch authority without remapping. x-kind drives parity tolerance: money = abs 0.005 (displayed to the cent); quantity/ratio = rel 1e-9 (abs 1e-9 near zero); count/label/flag = exact. */
export interface CalculationResponse {
  calculation_id: string;
  working_sequence: number;
  engine_version: string;
  reference_data_version: string;
  status: "completed";
  result: CalculationResultDTO;
  not_computed: Array<string>; // Result paths the engine does not compute yet (zero-filled in result). Shrinks to empty by M2.
  non_finite?: Record<string, "NaN" | "Infinity" | "-Infinity">; // Paths whose value was non-finite; the value in result is 0.
}

export interface CalculationResultDTO {
  totalDistance: number;
  totalEcaDistance: number;
  seaDaysBallast: number;
  seaDaysLaden: number;
  totalSeaDays: number;
  totalPortDays: number;
  extraSeaDays: number;
  extraPortDays: number;
  extraCanalDays: number;
  totalVoyageDays: number;
  baseSeaTime: number;
  seaMarginTime: number;
  hsfoConsumption: number;
  vlsfoConsumption: number;
  lsmgoConsumption: number;
  totalBunkerCost: number;
  effectiveFuelPrices: FuelMoney;
  nonEcaFuel: FuelQuantityWithTotal;
  ecaFuel: FuelQuantityWithTotal;
  nonEcaCo2: number;
  ecaCo2: number;
  nonEcaDistance: number;
  grossFreight: number;
  voyageCommission: number;
  netFreight: number;
  portCosts: number;
  miscCosts: number;
  canalCosts: number;
  totalVoyageCosts: number;
  hireCost: number;
  voyageCostInclHire: number;
  voyageCostExclHire: number;
  grossProfit: number;
  netProfit: number;
  tce: number;
  ntce: number;
  gtce: number;
  pAndL: number;
  totalCo2: number;
  co2Laden: number;
  co2Ballast: number;
  co2ByFuel: FuelQuantityWithTotal;
  efoi: number;
  afrCii: number;
  ciiRating: string;
  ciiResult: CiiResult;
  etsResult: EtsResult;
  etsCost: number;
  chargeableCo2: number;
  etsVoyageCoverage: number;
  etsPhaseIn: number;
  etsLegDetails: Array<EtsLegDetail>;
  ukEtsResult: UkEtsResult;
  ukEtsCost: number;
  ukChargeableCo2: number;
  ukEtsVoyageCoverage: number;
  ukEtsPhaseIn: number;
  ukEtsFreightImpact: number;
  emissionWarnings: Array<string>;
  emissionErrors: Array<string>;
  ladenDistance: number;
  transportWork?: number;
  grossRate: number;
  euCoveredFuel: FuelQuantity;
  totalCo2Cost: number;
  euaCo2Cost: number;
  euaFreightImpact: number;
  fuelEuResult: FuelEuResult;
  fuelEuTotalPenalty: number;
  fuelEuFreightImpact: number;
  perCargoBreakdown: Array<PerCargoBreakdown>;
  repositioningCost: number;
}

export interface FuelQuantity {
  hsfo: number;
  vlsfo: number;
  lsmgo: number;
}

export interface FuelQuantityWithTotal {
  hsfo: number;
  vlsfo: number;
  lsmgo: number;
  total: number;
}

export interface FuelMoney {
  hsfo: number;
  vlsfo: number;
  lsmgo: number;
}

export interface CiiResult {
  actualCii: number;
  requiredCii: number;
  ciiRatio: number;
  rating: string;
  ratingDescription: string;
  boundaries: {
    A: number;
    B: number;
    C: number;
    D: number;
  };
}

export interface EtsResult {
  totalCo2: number;
  etsVoyageCoverage: number;
  phaseInPercentage: number;
  chargeableCo2: number;
  etsCost: number;
  legBreakdown: Array<{
    origin: string;
    destination: string;
    coverage: number;
    co2: number;
    chargeableCo2: number;
  }>;
}

export interface EtsLegDetail {
  legIndex: number;
  isPortOnly: boolean;
  originPort: string;
  originUnloc: string;
  originIsEu: boolean;
  destPort: string;
  destUnloc: string;
  destIsEu: boolean;
  coveragePct: number;
  portCoveragePct: number;
  coverageLabel: string;
  seaVlsfo: number;
  seaLsmgo: number;
  seaHsfo: number;
  portVlsfo: number;
  portLsmgo: number;
  portHsfo: number;
  chargeableVlsfo: number;
  chargeableLsmgo: number;
  chargeableHsfo: number;
  chargeableCo2: number;
}

export interface UkEtsResult {
  phaseIn: number;
  ukCoveredFuel: FuelQuantity;
  ukCoveredCo2: number;
  chargeableCo2: number;
  ukEtsCost: number;
  ukVoyageCoverage: number;
  legBreakdown: Array<UkEtsLegDetail>;
}

export interface UkEtsLegDetail {
  legIndex: number;
  originPort: string;
  originZone: string | null;
  destPort: string;
  destZone: string | null;
  seaCoveragePct: number;
  portCoveragePct: number;
  ukCoveredFuel: FuelQuantity;
  ukCoveredCo2: number;
  chargeableCo2: number;
}

export interface FuelEuResult {
  voyageYear: number;
  ghgLimit: number;
  voyageGhg: number;
  totalEuEnergy: number;
  hsfoBalance: number;
  vlsfoBalance: number;
  mgoBalance: number;
  totalBalance: number;
  penaltyEur: number;
  totalPenalty: number;
  rewardFactor: number;
  fuels: {
    hsfo: FuelEuFuelDetail;
    vlsfo: FuelEuFuelDetail;
    lsmgo: FuelEuFuelDetail;
  };
  costPerTon: FuelMoney;
  legs: Array<FuelEuLegOutput>;
}

export interface FuelEuFuelDetail {
  fuelType: string;
  euQuantity: number;
  lcv: number;
  ghg: number;
  euEnergy: number;
  balance: number;
  penaltyEur: number;
  costPerTon: number;
  cost: number;
}

export interface FuelEuLegOutput {
  fromPort: string;
  toPort: string;
  fuelType: string;
  euFactor: number;
  euEnergy: number;
}

export interface PerCargoBreakdown {
  cargoId: number;
  cargoLabel: string;
  loadedQty: number;
  grossFreight: number;
  voyageCommissionAmount: number;
  netFreight: number;
  share: number;
  allocatedBunker: number;
  allocatedPortCosts: number;
  allocatedVoyageCosts: number;
  allocatedHire: number;
  grossRate: number;
  routeStartIdx: number;
  routeEndIdx: number;
  extraDays: number;
  demurrage: number;
  despatch: number;
  cargoDistanceNm: number;
  cargoTonMiles: number;
  tonMileShare: number;
  allocatedDirectPortCost: number;
  allocatedSharedPortCost: number;
  allocatedMiscCost: number;
  allocatedCanalCost: number;
  allocatedRepositioningCost: number;
  allocatedTotalCost: number;
  netRate: number;
  voyageCommissionPct: number;
}

