// GENERATED by look-up-service internal/realtime (tsgen_test.go) from the Go
// protocol types. Do not edit: run UPDATE_WS_PROTOCOL=1 go test ./internal/realtime
// and copy to cozy-crafting-cloud/src/contracts/ws/protocol.generated.ts.
import type { CalculationInput, CalculationResponse } from "../calc/types.generated";

export const PROTOCOL_VERSION = "ws.v1";

export const ERROR_CODES = [
  "VERSION_CONFLICT",
  "STALE_FENCE",
  "LEASE_HELD",
  "ENGINE_VERSION_CHANGED",
  "INVALID_PATCH",
  "UNAUTHORIZED",
  "RATE_LIMITED",
  "PAYLOAD_TOO_LARGE",
  "CALCULATION_FAILED",
  "CALCULATION_TIMEOUT",
  "INVALID_MESSAGE",
  "UNAVAILABLE",
  "ENGINE_VERSION_NEWER",
  "SESSION_LIMIT",
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export interface CalculationResultMessage {
  type: "calculation_result";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  generation: number;
  working_sequence: number;
  calculation_id: string;
  result: CalculationResponse;
}

export interface CalculationStartedMessage {
  type: "calculation_started";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  client_sequence: number;
  working_sequence: number;
  generation: number;
  calculation_id: string;
}

export interface CalculationSupersededMessage {
  type: "calculation_superseded";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  generation: number;
  calculation_id: string;
  superseded_by: number;
}

export interface ConflictMessage {
  type: "conflict";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  code: string;
  current_version?: number;
  expected_version?: number;
  current_engine_version?: string;
  fatal: boolean;
}

export interface ConnectMessage {
  type: "connect";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  sheet_id: string;
  segment: string;
  acknowledge_engine_change?: boolean;
  take_over?: boolean;
}

export interface ConnectedMessage {
  type: "connected";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  session_id: string;
  connection_id: string;
  working_sequence: number;
  persisted_version: number;
  last_client_sequence: number;
  dirty: boolean;
  engine_version: string;
  reference_data_version: string;
  sheet: CalculationInput["sheet"];
  limits: WireLimits;
}

export interface ErrorMessage {
  type: "error";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  code: string;
  message: string;
  retryable: boolean;
  fatal: boolean;
  client_sequence?: number;
  path?: string;
  expected_sequence?: number;
}

export interface PatchMessage {
  type: "patch";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  client_sequence: number;
  ops: PatchOp[];
}

export interface PingMessage {
  type: "ping";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
}

export interface PongMessage {
  type: "pong";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
}

export interface ResumeMessage {
  type: "resume";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  sheet_id: string;
  segment: string;
  session_id: string;
  last_client_sequence: number;
  last_working_sequence: number;
  acknowledge_engine_change?: boolean;
  take_over?: boolean;
  take_over_from?: string;
}

export interface ResumedMessage {
  type: "resumed";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  session_id: string;
  connection_id: string;
  working_sequence: number;
  persisted_version: number;
  last_client_sequence: number;
  dirty: boolean;
  engine_version: string;
  reference_data_version: string;
  sheet: CalculationInput["sheet"];
  limits: WireLimits;
}

export interface SaveMessage {
  type: "save";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
}

export interface SaveCompletedMessage {
  type: "save_completed";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  working_sequence: number;
  persisted_version: number;
  engine_version: string;
  engine_version_changed: boolean;
}

export interface SaveFailedMessage {
  type: "save_failed";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  working_sequence: number;
  code: string;
  retryable: boolean;
}

export interface SaveStartedMessage {
  type: "save_started";
  protocol_version: "ws.v1";
  message_id: string;
  request_id?: string;
  working_sequence: number;
}

export interface PatchOp {
  op: "set" | "remove";
  path: string;
  value?: unknown;
}

export interface WireLimits {
  max_message_bytes: number;
  max_ops_per_patch: number;
  heartbeat_seconds: number;
  idle_timeout_seconds: number;
}

export type ClientMessage =
  | ConnectMessage
  | PatchMessage
  | PingMessage
  | ResumeMessage
  | SaveMessage;

export type ServerMessage =
  | CalculationResultMessage
  | CalculationStartedMessage
  | CalculationSupersededMessage
  | ConflictMessage
  | ConnectedMessage
  | ErrorMessage
  | PongMessage
  | ResumedMessage
  | SaveCompletedMessage
  | SaveFailedMessage
  | SaveStartedMessage;
