/**
 * Client-side copy of the server's sheet patch allowlist (M7, D-037).
 *
 * patch-allowlist.v1.json is generated by the backend from the calc.v1 input
 * schema (contract/testdata) and copied here; scripts/golden/parity.sh checks
 * the copies are identical. The browser validates every operation with it
 * before sending, so invalid intermediate input (e.g. "13." in a number
 * field) is held back instead of being rejected by the server.
 */
import allowlistJson from "@/contracts/calc/patch-allowlist.v1.json";

export interface AllowEntry {
  path: string;
  types: string[];
  enum?: unknown[];
  pattern?: string;
  max_length?: number;
  max_items?: number;
  minimum?: number;
  max_abs?: number;
}

export type PatchOp = { op: "set"; path: string; value: unknown } | { op: "remove"; path: string };

export const MAX_OPS_PER_PATCH = 100;

interface Node {
  entry?: AllowEntry;
  children: Map<string, Node>; // literal segment, "*" (array index) or "{regex}" (map key)
  keyPattern?: RegExp;
}

function buildTree(entries: AllowEntry[]): Node {
  const root: Node = { children: new Map() };
  for (const e of entries) {
    let n = root;
    for (const seg of e.path.split("/").slice(1)) {
      let child = n.children.get(seg);
      if (!child) {
        child = { children: new Map() };
        if (seg.startsWith("{") && seg.endsWith("}")) child.keyPattern = new RegExp(seg.slice(1, -1));
        n.children.set(seg, child);
      }
      n = child;
    }
    n.entry = e;
  }
  return root;
}

const ROOT = buildTree(allowlistJson as AllowEntry[]);

function escapeSegment(s: string): string {
  return s.replace(/~/g, "~0").replace(/\//g, "~1");
}

export function pointer(segments: (string | number)[]): string {
  return "/" + segments.map((s) => escapeSegment(String(s))).join("/");
}

function childFor(n: Node, seg: string): Node | undefined {
  const lit = n.children.get(seg);
  if (lit) return lit;
  const star = n.children.get("*");
  if (star && (seg === "-" || /^(0|[1-9][0-9]*)$/.test(seg))) return star;
  for (const [k, c] of n.children) {
    if (k.startsWith("{") && c.keyPattern?.test(seg)) return c;
  }
  return undefined;
}

function resolve(path: string): Node | undefined {
  if (!path.startsWith("/")) return undefined;
  let n: Node | undefined = ROOT;
  for (const raw of path.slice(1).split("/")) {
    const seg = raw.replace(/~1/g, "/").replace(/~0/g, "~");
    n = n && childFor(n, seg);
    if (!n) return undefined;
  }
  return n;
}

function typeOf(v: unknown): string {
  if (v === null) return "null";
  if (Array.isArray(v)) return "array";
  return typeof v === "number" ? "number" : typeof v;
}

/** Checks a value (recursively) against the node's constraints. */
function checkValue(n: Node, v: unknown): string | null {
  const e = n.entry;
  if (!e) return "no constraint for path";
  const t = typeOf(v);
  const allowed = e.types.includes(t) || (t === "number" && e.types.includes("integer"));
  if (!allowed) return `type ${t} not allowed`;
  if (e.enum && !e.enum.some((x) => x === v)) return "value not in the allowed set";
  switch (t) {
    case "number": {
      const x = v as number;
      if (!Number.isFinite(x)) return "number is not finite";
      if (e.max_abs !== undefined && Math.abs(x) > e.max_abs) return "number out of range";
      if (!e.types.includes("number") && !Number.isInteger(x)) return "integer required";
      if (e.minimum !== undefined && x < e.minimum) return "number below minimum";
      return null;
    }
    case "string": {
      const s = v as string;
      if (e.max_length !== undefined && s.length > e.max_length) return "string too long";
      if (e.pattern && !new RegExp(e.pattern).test(s)) return "string does not match the format";
      return null;
    }
    case "array": {
      const a = v as unknown[];
      if (e.max_items !== undefined && a.length > e.max_items) return "too many array items";
      const item = n.children.get("*");
      if (!item) return "array items not allowed";
      for (const x of a) {
        const err = checkValue(item, x);
        if (err) return err;
      }
      return null;
    }
    case "object": {
      for (const [k, x] of Object.entries(v as Record<string, unknown>)) {
        if (x === undefined) continue;
        const c = childFor(n, k);
        if (!c || c === n.children.get("*")) return `unknown field ${k}`;
        const err = checkValue(c, x);
        if (err) return err;
      }
      return null;
    }
    default:
      return null;
  }
}

/** Validates one operation; null when it is acceptable to send. */
export function validateOp(op: PatchOp): string | null {
  const n = resolve(op.path);
  if (!n) return "path not allowed";
  if (op.op === "remove") return null;
  return checkValue(n, op.value);
}

/**
 * Projects a document onto the allowlist: drops fields the contract does not
 * define (the server would reject them) and reports their paths.
 */
export function projectDocument(doc: unknown, dropped: string[] = []): unknown {
  const walk = (n: Node, v: unknown, path: string): unknown => {
    if (v === null || typeof v !== "object") return v;
    if (Array.isArray(v)) {
      const item = n.children.get("*");
      return item ? v.map((x, i) => walk(item, x, `${path}/${i}`)) : v;
    }
    const out: Record<string, unknown> = {};
    for (const [k, x] of Object.entries(v as Record<string, unknown>)) {
      if (x === undefined) continue;
      const c = childFor(n, k);
      if (!c || c === n.children.get("*")) {
        dropped.push(`${path}/${escapeSegment(k)}`);
        continue;
      }
      out[k] = walk(c, x, `${path}/${escapeSegment(k)}`);
    }
    return out;
  };
  return walk(ROOT, JSON.parse(JSON.stringify(doc ?? {})), "");
}
